# Generated by Django 6.0.4 on 2026-04-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicebooking_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='address',
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service'),
        ),
        migrations.DeleteModel(
            name='OperatorProfile',
        ),
    ]
