# Generated by Django 6.0.4 on 2026-04-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_price_operatorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='services.service'),
        ),
    ]
