# Generated by Django 6.0.4 on 2026-04-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_servicebooking_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
