# Generated by Django 6.0.4 on 2026-04-22 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='adnan', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='khalid', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='abc@gmail.com', max_length=254, null=True)),
                ('phone', models.CharField(default=0, max_length=250)),
                ('address', models.TextField(blank=True, default='buttchowk', null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.products')),
            ],
        ),
    ]
