# Generated by Django 6.0.4 on 2026-04-22 18:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('type', models.CharField(choices=[('IN', 'INTERIOR'), ('EX', 'EXTERIOR'), ('MCH', 'MECHANICAL'), ('RM', 'RIMS'), ('SPI', 'SPOILER'), ('WRP', 'WRAPS'), ('LED', 'LEDLIGHTS'), ('ACS', 'ACCESSORIES'), ('TR', 'TYRES')], max_length=4)),
                ('details', models.TextField(default='empty', max_length=500)),
                ('warranty', models.CharField(default='N/A', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
